# Generated by Django 6.0.6 on 2026-06-13 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WCMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveSmallIntegerField(unique=True)),
                ('team_a', models.CharField(max_length=40)),
                ('team_b', models.CharField(max_length=40)),
                ('team_a_code', models.CharField(max_length=3)),
                ('team_b_code', models.CharField(max_length=3)),
                ('round', models.CharField(choices=[('group', 'Vòng bảng'), ('round32', 'Vòng 1/32'), ('round16', 'Vòng 1/16'), ('quarter', 'Tứ kết'), ('semi', 'Bán kết'), ('final', 'Chung kết')], max_length=10)),
                ('group_name', models.CharField(blank=True, default='', max_length=2)),
                ('match_time', models.DateTimeField()),
                ('score_a', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_b', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Sắp diễn ra'), ('live', 'Đang diễn ra'), ('finished', 'Kết thúc')], default='upcoming', max_length=10)),
                ('points_pool', models.PositiveIntegerField(default=1000)),
            ],
            options={
                'verbose_name': 'WC Match',
                'ordering': ['match_time', 'match_number'],
            },
        ),
        migrations.CreateModel(
            name='WCPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('total_points', models.IntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wc_player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points', 'nickname'],
            },
        ),
        migrations.CreateModel(
            name='WCPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(choices=[('win_a', 'Đội A thắng'), ('draw', 'Hòa'), ('win_b', 'Đội B thắng')], max_length=5)),
                ('points_earned', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='wc2026.wcmatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='wc2026.wcplayer')),
            ],
            options={
                'ordering': ['-match__match_time'],
                'unique_together': {('player', 'match')},
            },
        ),
    ]
