# Generated by Django 6.0.5 on 2026-05-27 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableleave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='availableleave',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='availableleave',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='availableleave',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='companyleave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='companyleave',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='companyleave',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='companyleave',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='compensatoryleaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='compensatoryleaverequest',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='compensatoryleaverequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='compensatoryleaverequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='compensatoryleaverequestcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='compensatoryleaverequestcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='compensatoryleaverequestcomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='compensatoryleaverequestcomment',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='employeepastleaverestrict',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='employeepastleaverestrict',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='employeepastleaverestrict',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='employeepastleaverestrict',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='historicalavailableleave',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='historicalavailableleave',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='historicalavailableleave',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='historicalavailableleave',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='historicalcompensatoryleaverequest',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='historicalcompensatoryleaverequest',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='historicalcompensatoryleaverequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='historicalcompensatoryleaverequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='historicalleaveallocationrequest',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='historicalleaveallocationrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='historicalleaveallocationrequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='historicalleaveallocationrequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='historicalleaverequest',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='historicalleaverequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='historicalleaverequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='leaveallocationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='leaveallocationrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='leaveallocationrequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='leaveallocationrequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='leaveallocationrequestcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='leaveallocationrequestcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='leaveallocationrequestcomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='leaveallocationrequestcomment',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='leavegeneralsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='leavegeneralsetting',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='leavegeneralsetting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='leavegeneralsetting',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='leaverequestcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='leaverequestcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='leaverequestcomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='leaverequestcomment',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='restrictleave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='restrictleave',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='restrictleave',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='restrictleave',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
    ]
