# Generated by Django 6.0 on 2026-05-09 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_user_is_new_employee'),
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lượt xem dashboard',
                'verbose_name_plural': 'Lượt xem dashboard',
            },
        ),
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('to_do', 'Cần làm'), ('in_progress', 'Đang làm'), ('done', 'Hoàn thành'), ('blocked', 'Bị chặn')], default='to_do', max_length=20, verbose_name='Trạng thái')),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('normal', 'Bình thường'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='normal', max_length=20, verbose_name='Ưu tiên')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('recurrence_rule', models.CharField(choices=[('none', 'Không lặp'), ('daily', 'Hằng ngày'), ('weekly', 'Hằng tuần'), ('monthly', 'Hằng tháng')], default='none', max_length=20, verbose_name='Lặp lại')),
                ('next_occurrence_created', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to='employee.employee', verbose_name='Người giao')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to='employee.employee', verbose_name='Giao cho')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='base.department', verbose_name='Phòng ban')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='eoffice.worktask', verbose_name='Thuộc công việc cha')),
            ],
            options={
                'verbose_name': 'Công việc',
                'verbose_name_plural': 'Danh sách công việc',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('body', models.TextField(verbose_name='Nội dung')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to='employee.employee', verbose_name='Người bình luận')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='eoffice.worktask', verbose_name='Công việc')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận công việc',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='worktask',
            index=models.Index(fields=['status', 'recurrence_rule', 'next_occurrence_created'], name='worktask_recur_cron_idx'),
        ),
        migrations.AddIndex(
            model_name='worktask',
            index=models.Index(fields=['assigned_to', 'is_active'], name='worktask_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='worktask',
            index=models.Index(fields=['department', 'is_active'], name='worktask_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='worktask',
            index=models.Index(fields=['due_date', 'status'], name='worktask_overdue_idx'),
        ),
    ]
