# Generated by Django 6.0.5 on 2026-05-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_tourschedule_leave_allocated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourguide',
            name='languages',
            field=models.CharField(blank=True, help_text='Ví dụ: Tiếng Việt, Tiếng Anh, Tiếng Pháp', max_length=300, verbose_name='Ngôn ngữ dẫn tour'),
        ),
        migrations.AlterField(
            model_name='tourguide',
            name='specialization',
            field=models.CharField(blank=True, help_text='Ví dụ: Hà Nội - Hạ Long, Miền Tây', max_length=300, verbose_name='Chuyên môn / Tuyến tour'),
        ),
    ]
