# Generated by Django 6.0.5 on 2026-05-27 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='candidatedocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='candidatedocument',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='candidatedocument',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='candidatedocument',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='candidatedocumentrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='candidatedocumentrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='candidatedocumentrequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='candidatedocumentrequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='candidaterating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='candidaterating',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='candidaterating',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='candidaterating',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='historicalrejectedcandidate',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='historicalrejectedcandidate',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='historicalrejectedcandidate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='historicalrejectedcandidate',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='linkedinaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='linkedinaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='linkedinaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='linkedinaccount',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='questionordering',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='questionordering',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='questionordering',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='questionordering',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='recruitmentgeneralsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='recruitmentgeneralsetting',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='recruitmentgeneralsetting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='recruitmentgeneralsetting',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='recruitmentsurvey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='recruitmentsurvey',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='recruitmentsurvey',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='recruitmentsurvey',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='recruitmentsurveyanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='recruitmentsurveyanswer',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='recruitmentsurveyanswer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='recruitmentsurveyanswer',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='rejectedcandidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='rejectedcandidate',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='rejectedcandidate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='rejectedcandidate',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='rejectreason',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='rejectreason',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='rejectreason',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='rejectreason',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='skillzone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='skillzone',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='skillzone',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='skillzone',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='skillzonecandidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='skillzonecandidate',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='skillzonecandidate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='skillzonecandidate',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='stagefiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='stagefiles',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='stagefiles',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='stagefiles',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='stagenote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='stagenote',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='stagenote',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='stagenote',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
    ]
