# Generated by Django 6.0.5 on 2026-05-27 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_work_level'),
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actiontype',
            options={'verbose_name': 'Loại hành động', 'verbose_name_plural': 'Các loại hành động'},
        ),
        migrations.AlterModelOptions(
            name='employeebankdetails',
            options={'verbose_name': 'Chi tiết ngân hàng nhân viên', 'verbose_name_plural': 'Chi tiết ngân hàng nhân viên'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Chính sách', 'verbose_name_plural': 'Chính sách'},
        ),
        migrations.AlterField(
            model_name='actiontype',
            name='block_option',
            field=models.BooleanField(default=False, help_text='If is enabled, employees log in will be blocked based on period of suspension or dismissal.', verbose_name='Kích hoạt khối đăng nhập:'),
        ),
        migrations.AlterField(
            model_name='actiontype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='actiontype',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='actiontype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='actiontype',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='bonuspoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='bonuspoint',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='bonuspoint',
            name='encashment_condition',
            field=models.CharField(blank=True, choices=[('==', 'bằng'), ('>', 'vắt hơn'), ('<', 'ít hơn'), ('>=', 'lớn hơn hoặc bằng'), ('<=', 'nhỏ hơn hoặc bằng')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bonuspoint',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='bonuspoint',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='employee_id',
            field=models.ManyToManyField(to='employee.employee', verbose_name='Người lao động'),
        ),
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='unit_in',
            field=models.CharField(choices=[('days', 'Ngày'), ('hours', 'Giờ')], default='days', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_first_name',
            field=models.CharField(max_length=200, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Họ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_get', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='employee_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_bank_details', to='employee.employee', verbose_name='Người lao động'),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='employeegeneralsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='employeegeneralsetting',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='employeegeneralsetting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='employeegeneralsetting',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='employeenote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='employeenote',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='employeenote',
            name='description',
            field=models.TextField(null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='employeenote',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='employeenote',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='employeetag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='employeetag',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='employeetag',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='employeetag',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='employeetag',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='basic_salary',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lương cơ bản'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc hợp đồng'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='date_joining',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày tham gia'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.department', verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email công việc'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='employee_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_work_info', to='employee.employee', verbose_name='Người lao động'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='employee_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.employeetype', verbose_name='Loại Nhân viên'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='job_position_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.jobposition', verbose_name='Vị trí công việc'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='job_role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.jobrole', verbose_name='Vai trò Công việc'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Địa điểm làm việc'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='mobile',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Điện thoại cơ quan'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='reporting_manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporting_manager', to='employee.employee', verbose_name='Người quản lý Báo cáo'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='salary_hour',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lương mỗi giờ'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='shift_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.employeeshift', verbose_name='Ca'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='employee.employeetag', verbose_name='Thẻ nhân viên'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='work_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.worktype', verbose_name='Loại Công việc'),
        ),
        migrations.AlterField(
            model_name='historicalbonuspoint',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='historicalbonuspoint',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='historicalbonuspoint',
            name='encashment_condition',
            field=models.CharField(blank=True, choices=[('==', 'bằng'), ('>', 'vắt hơn'), ('<', 'ít hơn'), ('>=', 'lớn hơn hoặc bằng'), ('<=', 'nhỏ hơn hoặc bằng')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbonuspoint',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='historicalbonuspoint',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='basic_salary',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lương cơ bản'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='company_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc hợp đồng'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='date_joining',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày tham gia'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='department_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.department', verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email công việc'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='employee_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.employee', verbose_name='Người lao động'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='employee_type_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.employeetype', verbose_name='Loại Nhân viên'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='job_position_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.jobposition', verbose_name='Vị trí công việc'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='job_role_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.jobrole', verbose_name='Vai trò Công việc'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Địa điểm làm việc'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='mobile',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Điện thoại cơ quan'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='reporting_manager_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.employee', verbose_name='Người quản lý Báo cáo'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='salary_hour',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lương mỗi giờ'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='shift_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.employeeshift', verbose_name='Ca'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='work_type_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.worktype', verbose_name='Loại Công việc'),
        ),
        migrations.AlterField(
            model_name='notefiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='notefiles',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='notefiles',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='notefiles',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='company_id',
            field=models.ManyToManyField(blank=True, to='base.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='policymultiplefile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='policymultiplefile',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='policymultiplefile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='policymultiplefile',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='profileeditfeature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='profileeditfeature',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='profileeditfeature',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='profileeditfeature',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.CreateModel(
            name='WorkLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('level_number', models.PositiveSmallIntegerField(unique=True, verbose_name='Cấp bậc (1–8)')),
                ('name', models.CharField(max_length=100, verbose_name='Tên cấp bậc')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('color', models.CharField(default='#6c757d', max_length=20, verbose_name='Màu')),
                ('bhxh_salary', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Lương đóng BHXH (VNĐ/tháng)')),
                ('income_min', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Thu nhập năm tối thiểu (VNĐ)')),
                ('income_max', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Thu nhập năm tối đa (VNĐ)')),
                ('wfh_days_per_week', models.PositiveSmallIntegerField(default=0, verbose_name='Số ngày WFH/tuần')),
                ('life_insurance_annual', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Bảo hiểm nhân thọ (VNĐ/năm)')),
                ('family_health_insurance', models.BooleanField(default=False, verbose_name='BHYT bổ sung gia đình')),
                ('family_health_insurance_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Mức BHYT bổ sung (VNĐ/năm)')),
                ('extra_leave_days', models.PositiveSmallIntegerField(default=0, verbose_name='Ngày phép thêm/năm')),
                ('allowance_position', models.BooleanField(default=False, verbose_name='Phụ cấp chức vụ')),
                ('allowance_housing', models.BooleanField(default=False, verbose_name='Phụ cấp nhà ở')),
                ('allowance_transport', models.BooleanField(default=False, verbose_name='Phụ cấp di chuyển')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Công ty')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi')),
            ],
            options={
                'verbose_name': 'Cấp bậc',
                'verbose_name_plural': 'Cấp bậc',
                'ordering': ['level_number'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='work_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employee.worklevel', verbose_name='Cấp bậc'),
        ),
    ]
