"""
Django settings for horilla project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from os.path import join
from pathlib import Path

import environ
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

env = environ.Env(
    DEBUG=(bool, True),
    SECRET_KEY=(
        str,
        "django-insecure-j8op9)1q8$1&0^s&p*_0%d#pr@w9qj@1o=3#@d=a(^@9@zd@%j",
    ),
    ALLOWED_HOSTS=(list, ["*"]),
    CSRF_TRUSTED_ORIGINS=(list, ["http://localhost:8000"]),
)

env.read_env(os.path.join(BASE_DIR, ".env"), overwrite=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")

# Application definition

THEME_APP = "horilla_theme"


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "mozilla_django_oidc",
    "notifications",
    "mathfilters",
    "corsheaders",
    "simple_history",
    "django_filters",
    THEME_APP,
    "base",
    "employee",
    "recruitment",
    "leave",
    "pms",
    "onboarding",
    "asset",
    "attendance",
    "payroll",
    "training",
    "promotion",
    "widget_tweaks",
    "django_apscheduler",
]
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"

APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "horilla.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": False,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": [
                (
                    "django.template.loaders.filesystem.Loader",
                    [BASE_DIR / THEME_APP / "templates"],
                ),
                "django.template.loaders.app_directories.Loader",
                ("django.template.loaders.filesystem.Loader", [BASE_DIR / "templates"]),
            ],
        },
    },
]

WSGI_APPLICATION = "horilla.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

if env("DATABASE_URL", default=None):
    DATABASES = {
        "default": env.db(),
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": env("DB_ENGINE", default="django.db.backends.sqlite3"),
            "NAME": env(
                "DB_NAME",
                default=os.path.join(
                    BASE_DIR,
                    "TestDB.sqlite3",
                ),
            ),
            "USER": env("DB_USER", default=""),
            "PASSWORD": env("DB_PASSWORD", default=""),
            "HOST": env("DB_HOST", default=""),
            "PORT": env("DB_PORT", default=""),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MESSAGE_TAGS = {
    messages.DEBUG: "oh-alert--warning",
    messages.INFO: "oh-alert--info",
    messages.SUCCESS: "oh-alert--success",
    messages.WARNING: "oh-alert--warning",
    messages.ERROR: "oh-alert--danger",
}


CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS")

LOGIN_URL = "/login"


SIMPLE_HISTORY_REVERT_DISABLED = True


DJANGO_NOTIFICATIONS_CONFIG = {
    "USE_JSONFIELD": True,
    "SOFT_DELETE": True,
    "USE_WATCHED": True,
    "NOTIFICATIONS_STORAGE": "notifications.storage.DatabaseStorage",
    "TEMPLATE": "notifications.html",  # Add this line
}

X_FRAME_OPTIONS = "SAMEORIGIN"

LANGUAGES = (
    ("en", "English (US)"),
    ("vi", "Tiếng Việt"),
#    ("de", "Deutsche"),
#    ("es", "Español"),
    ("fr", "Français"),
#    ("ar", "عربى"),
#   ("pt-br", "Português (Brasil)"),
#    ("zh-hans", "Simplified Chinese"),
#    ("zh-hant", "Traditional Chinese"),
#    ("it", "Italian"),
)

LOCALE_PATHS = [
    join(BASE_DIR, "horilla", "locale"),
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "vi"

TIME_ZONE = env("TIME_ZONE", default="Asia/Ho_Chi_Minh")

USE_I18N = True

USE_L10N = True

USE_TZ = True


# LDAP Configuration
# import ldap
# from django_auth_ldap.config import LDAPSearch, GroupOfNamesType

AUTH_LDAP_SERVER_URI = "ldap://127.0.0.1:389"  # Replace with your LDAP server address

# Bind credentials, if required
AUTH_LDAP_BIND_DN = "cn=admin,dc=horilla,dc=com"  # Replace with your bind DN
AUTH_LDAP_BIND_PASSWORD = "your_password"  # Replace with your LDAP bind password

# Define the search base and user lookup
# AUTH_LDAP_USER_SEARCH = LDAPSearch("ou=users,dc=horilla,dc=com", ldap.SCOPE_SUBTREE, "(uid=%(user)s)")

# Map LDAP fields to Django user fields
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

# ── OIDC / Keycloak SSO ─────────────────────────────────────────────
KC_BASE = env("OIDC_KC_BASE", default="https://sso.hnhtravel.work/realms/HNHTravel-SGN")
OIDC_RP_CLIENT_ID = env("OIDC_RP_CLIENT_ID", default="horilla-hrm")
OIDC_RP_CLIENT_SECRET = env("OIDC_RP_CLIENT_SECRET")
OIDC_OP_AUTHORIZATION_ENDPOINT = f"{KC_BASE}/protocol/openid-connect/auth"
OIDC_OP_TOKEN_ENDPOINT = f"{KC_BASE}/protocol/openid-connect/token"
OIDC_OP_USER_ENDPOINT = f"{KC_BASE}/protocol/openid-connect/userinfo"
OIDC_OP_JWKS_ENDPOINT = f"{KC_BASE}/protocol/openid-connect/certs"
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_SCOPES = "openid email profile"
OIDC_VERIFY_SSL = env.bool("OIDC_VERIFY_SSL", default=False)
# Sau khi đăng nhập, mặc định đưa về giao diện PWA (mobile-first) cho mọi user.
# Admin/HR vẫn vào desktop HRM bằng URL trực tiếp (/login, /employee/..., /admin/).
LOGIN_REDIRECT_URL = "/pwa/"
LOGOUT_REDIRECT_URL = "/login"
OIDC_USERNAME_ALGO = "horilla.oidc_backend.generate_username"
OIDC_AUTHENTICATION_BACKEND = "horilla.oidc_backend.HorillaOIDCBackend"
OIDC_STORE_ACCESS_TOKEN = True
OIDC_STORE_ID_TOKEN = True
OIDC_REDIRECT_BASE_URL = env("OIDC_REDIRECT_BASE_URL", default="https://qlns.hnhtravel.work")

# ── Keycloak Admin API ─────────────────────────────────────────────
KC_SERVER_URL = env("KC_SERVER_URL", default="https://sso.hnhtravel.work")
KC_REALM = env("KC_REALM", default="HNHTravel-SGN")
KC_ADMIN_CLIENT_ID = env("KC_ADMIN_CLIENT_ID", default="admin-cli")
KC_ADMIN_CLIENT_SECRET = env("KC_ADMIN_CLIENT_SECRET", default="")
KC_ADMIN_USERNAME = env("KC_ADMIN_USERNAME", default="admin")
KC_ADMIN_PASSWORD = env("KC_ADMIN_PASSWORD", default="Admin@2711")

# ── Email (SMTP) ───────────────────────────────────────────────────
EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = int(env("EMAIL_PORT", default="587"))
EMAIL_USE_TLS = env("EMAIL_USE_TLS", default="True") == "True"
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="HNH Travel <noreply@hongngocha.com>")
HNH_PWA_URL = env("HNH_PWA_URL", default="https://qlns.hnhtravel.work/pwa")
HNH_COO_EMAIL = env("HNH_COO_EMAIL", default="coo@hongngocha.com")

# ── External Task System (1StopShop) deeplink ─────────────────────
TASK_SYSTEM_URL = env("TASK_SYSTEM_URL", default="https://task.hnhtravel.work")
TASK_KC_CLIENT_ID = env("TASK_KC_CLIENT_ID", default="")

# Trust Cloudflare/nginx reverse proxy HTTPS headers
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
# ────────────────────────────────────────────────────────────────────

# ── Web Push Notifications (VAPID) ────────────────────────────────
VAPID_PUBLIC_KEY = env(
    "VAPID_PUBLIC_KEY",
    default="BN_pBg64Zg504PSFLtSJoNnDnEPI74mHm-oq-FaYh88KZWou1xiQ44W_7mC1VLkk0ImTvepK3izbzRApDfdSYhM",
)
VAPID_PRIVATE_KEY = env(
    "VAPID_PRIVATE_KEY",
    default="xntjHaCqI_jWWONEJvPGyIh56c27I2tvVXxa7cC6jgY",
)
VAPID_ADMIN_EMAIL = env("VAPID_ADMIN_EMAIL", default="anhquankcn2412@gmail.com")
# ────────────────────────────────────────────────────────────────────

AUTHENTICATION_BACKENDS = [
    #    "django_auth_ldap.backend.LDAPBackend",
    "horilla.oidc_backend.HorillaOIDCBackend",
    "django.contrib.auth.backends.ModelBackend",
]
AUTH_LDAP_ALWAYS_UPDATE_USER = True
