# Generated by Django 6.0.5 on 2026-05-27 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_is_new_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='announcementcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='announcementcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='announcementcomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='announcementcomment',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='company',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='companyleaves',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='companyleaves',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='companyleaves',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='companyleaves',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='dashboardemployeecharts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='dashboardemployeecharts',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='dashboardemployeecharts',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='dashboardemployeecharts',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='department',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='employeeshiftschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='employeeshiftschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='employeeshiftschedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='employeeshiftschedule',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='historicalrotatingshiftassign',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='historicalrotatingshiftassign',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='historicalrotatingshiftassign',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='historicalrotatingshiftassign',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='historicalrotatingworktypeassign',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='historicalrotatingworktypeassign',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='historicalrotatingworktypeassign',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='historicalrotatingworktypeassign',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='historicalshiftrequest',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='historicalshiftrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='historicalshiftrequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='historicalshiftrequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='historicalworktyperequest',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='historicalworktyperequest',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='historicalworktyperequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='historicalworktyperequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='horillamailtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='horillamailtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='horillamailtemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='horillamailtemplate',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='integrationapps',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='integrationapps',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='integrationapps',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='integrationapps',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='multipleapprovalcondition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='multipleapprovalcondition',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='multipleapprovalcondition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='multipleapprovalcondition',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='penaltyaccounts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='penaltyaccounts',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='penaltyaccounts',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='penaltyaccounts',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='rotatingshift',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='rotatingshift',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='rotatingshift',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='rotatingshift',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='rotatingshiftassign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='rotatingshiftassign',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='rotatingshiftassign',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='rotatingshiftassign',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='rotatingworktype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='rotatingworktype',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='rotatingworktype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='rotatingworktype',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='rotatingworktypeassign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='rotatingworktypeassign',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='rotatingworktypeassign',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='rotatingworktypeassign',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='shiftrequestcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='shiftrequestcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='shiftrequestcomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='shiftrequestcomment',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='tracklatecomeearlyout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='tracklatecomeearlyout',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='tracklatecomeearlyout',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='tracklatecomeearlyout',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='worktyperequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='worktyperequest',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='worktyperequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='worktyperequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='worktyperequestcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='worktyperequestcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='worktyperequestcomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='worktyperequestcomment',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
    ]
