# Generated by Django 6.0.5 on 2026-05-31 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_work_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='KCRoleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kc_role_id', models.CharField(max_length=255, verbose_name='KC Role ID')),
                ('kc_role_name', models.CharField(max_length=255, verbose_name='KC Role Name')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Last Synced')),
                ('job_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kc_mapping', to='base.jobrole', verbose_name='Job Role')),
            ],
            options={
                'verbose_name': 'KC Role Mapping',
                'verbose_name_plural': 'KC Role Mappings',
                'db_table': 'base_kcrolemapping',
            },
        ),
    ]
