# Generated by Django 6.0.5 on 2026-05-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_kc_role_mapping'),
        ('employee', '0002_work_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='KCUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kc_user_id', models.CharField(max_length=255, verbose_name='KC User ID')),
                ('kc_username', models.CharField(max_length=255, verbose_name='KC Username')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Last Synced')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kc_mapping', to='employee.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'KC User Mapping',
                'verbose_name_plural': 'KC User Mappings',
                'db_table': 'base_kcusermapping',
            },
        ),
    ]
