# Generated by Django 6.0 on 2026-06-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_appfeature_labelday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appfeature',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='appfeature',
            name='is_base',
            field=models.BooleanField(default=False, help_text='Nếu bật, tính năng này luôn hiển thị cho mọi user bất kể cấu hình nhóm quyền.', verbose_name='Luôn hiển thị'),
        ),
        migrations.AlterField(
            model_name='departmentshift',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupappvisibility',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hrmconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
