# Generated by Django 6.0.5 on 2026-05-27 18:42

import django.db.models.deletion
import horilla.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_work_level'),
        ('horilla_documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Tài liệu', 'verbose_name_plural': 'Hồ sơ'},
        ),
        migrations.AlterModelOptions(
            name='documentrequest',
            options={'verbose_name': 'Yêu cầu tài liệu', 'verbose_name_plural': 'Yêu cầu tài liệu'},
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to=horilla.models.upload_path, verbose_name='Tài liệu'),
        ),
        migrations.AlterField(
            model_name='document',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Người lao động'),
        ),
        migrations.AlterField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_digital_asset',
            field=models.BooleanField(default=False, verbose_name='Là tài sản kỹ thuật số'),
        ),
        migrations.AlterField(
            model_name='document',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày phát hành'),
        ),
        migrations.AlterField(
            model_name='document',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='document',
            name='notify_before',
            field=models.IntegerField(default=1, null=True, verbose_name='Thông báo trước'),
        ),
        migrations.AlterField(
            model_name='document',
            name='reject_reason',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Lý do từ chối'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=10, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Được tạo tại'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Được tạo bởi'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='employee_id',
            field=models.ManyToManyField(to='employee.employee', verbose_name='Người lao động'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='format',
            field=models.CharField(choices=[('any', 'Any'), ('pdf', 'PDF'), ('txt', 'TXT'), ('docx', 'DOCX'), ('xlsx', 'XLSX'), ('jpg', 'JPG'), ('png', 'PNG'), ('jpeg', 'JPEG')], max_length=10, verbose_name='Định dạng'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='max_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kích thước tối đa (Tính bằng MB)'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Được sửa đổi Bởi'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tiêu đề'),
        ),
    ]
