# Generated by Django 6.0 on 2026-05-28 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_created_at_and_more'),
        ('employee', '0002_work_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSCheckInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('distance_m', models.FloatField()),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='attendance_selfies/')),
                ('source', models.CharField(default='pwa', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_offline_sync', models.BooleanField(default=False)),
                ('attendance_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendanceactivity')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_checkin_logs', to='employee.employee')),
            ],
            options={
                'verbose_name': 'GPS Check-in Log',
                'verbose_name_plural': 'GPS Check-in Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
