# Generated by Django 6.0 on 2026-06-07 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_workrecords_message_maxlength'),
        ('base', '0019_add_target_departments'),
        ('employee', '0003_worklevel_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employeeshiftplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ShiftChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_shift_requests', to='employee.employee', verbose_name='Người duyệt')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_change_requests', to='employee.employee', verbose_name='Nhân viên')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_shift_requests', to='employee.employee', verbose_name='Người đề xuất')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='base.employeeshift', verbose_name='Ca làm việc')),
            ],
            options={
                'verbose_name': 'Shift Change Request',
                'verbose_name_plural': 'Shift Change Requests',
                'db_table': 'attendance_shiftchangerequest',
                'ordering': ['-created_at'],
            },
        ),
    ]
