# Generated by Django 6.0.7 on 2026-09-07 14:33
# Tay chinh: bo AlterField wifiattendancerange.id (drift model co san, khong
# lien quan tinh nang nay) khoi ban makemigrations tu dong sinh ra.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_wifi_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricPendingPunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_sn', models.CharField(max_length=64, verbose_name='Serial máy chấm công')),
                ('device_user_id', models.CharField(max_length=64, verbose_name='User ID trên máy')),
                ('punch_at', models.DateTimeField(verbose_name='Thời điểm chấm (trên máy)')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm server nhận')),
            ],
            options={
                'verbose_name': 'Biometric Pending Punch',
                'verbose_name_plural': 'Biometric Pending Punches',
                'db_table': 'attendance_biometricpendingpunch',
                'ordering': ['punch_at'],
                'unique_together': {('device_sn', 'device_user_id', 'punch_at')},
            },
        ),
        migrations.CreateModel(
            name='BiometricDeviceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_sn', models.CharField(max_length=64, verbose_name='Serial máy chấm công')),
                ('device_user_id', models.CharField(max_length=64, verbose_name='User ID trên máy')),
                ('ignored', models.BooleanField(default=False, verbose_name='Bỏ qua (không map)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người map')),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_device_mappings', to='employee.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Biometric Device Mapping',
                'verbose_name_plural': 'Biometric Device Mappings',
                'db_table': 'attendance_biometricdevicemapping',
                'unique_together': {('device_sn', 'device_user_id')},
            },
        ),
    ]
