# Generated by Django 6.0 on 2026-06-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_add_target_departments'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='target_departments',
            field=models.ManyToManyField(blank=True, related_name='training_courses', to='base.department', verbose_name='Target Departments'),
        ),
    ]
