name: Deploy Production

on:
  push:
    branches: [1.0]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, production]
    timeout-minutes: 15
    steps:
      - name: Deploy to production
        run: |
          cd /opt/hnh/horilla
          sudo bash deploy-prod.sh
